apiVersion: apps/v1
kind: Deployment
metadata:
  name: crypto-service
spec:
  selector:
    matchLabels:
      app: crypto-service
  template:
    metadata:
      labels:
        app: crypto-service
    spec:
      containers:
      - name: crypto-service
        image: crypto-service
        imagePullPolicy: Never
        resources:
          limits:
            memory: "128Mi"
            cpu: "200m"
        ports:
        - containerPort: 8083
---
apiVersion: v1
kind: Service
metadata:
  name: crypto-service
spec:
  selector:
    app: crypto-service
  ports:
  - port: 8083