apiVersion: apps/v1
kind: Deployment
metadata:
  name: market-service
spec:
  selector:
    matchLabels:
      app: market-service
  template:
    metadata:
      labels:
        app: market-service
    spec:
      containers:
      - name: market-service
        image: market-service
        imagePullPolicy: Never
        resources:
          limits:
            memory: "128Mi"
            cpu: "200m"
        ports:
        - containerPort: 8082
        env:
        - name: COINMARKETCAP_API_KEY
          valueFrom:
            secretKeyRef:
              name: market-secret
              key: COINMARKETCAP_API_KEY
---
apiVersion: v1
kind: Service
metadata:
  name: market-service
spec:
  selector:
    app: market-service
  ports:
  - port: 8082